name: 'transport_retail_dbt_duck_project'
version: '1.0.0'
config-version: 2

profile: 'transport_retail_dbt_duck_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  transport_retail_dbt_duck_project:
    staging:
      +materialized: view
    marts:
      core:
        +materialized: table

